defmodule SpreadSheetAi.Agents.Factory do
  @behaviour Sagents.Factory

  @moduledoc """
  Builds the spreadsheet copilot agent for a conversation.

  Generated by `mix sagents.setup`, then cut down to what the copilot uses
  (docs/backend-plan.md §7.2):

  - models from `SpreadSheetAi.Agents.ChatModels` (OpenRouter by default,
    a scripted model in tests), with no fallback models;
  - middleware: `ConversationTitle`, `Summarization` and `PatchToolCalls`.
    `SpreadSheetAi.Agents.Middleware.SheetTools` joins them in Phase 8.
    There is no filesystem, todo list, sub-agents, questions or
    human-in-the-loop.

  Pairs with `SpreadSheetAi.Agents.FactoryConfig`, which says what a config
  holds and how to build one.
  """

  alias Sagents.Agent
  alias Sagents.Middleware.ConversationTitle
  alias SpreadSheetAi.Agents.ChatModels
  alias SpreadSheetAi.Agents.FactoryConfig

  @doc """
  Builds a `%Sagents.Agent{}` from the supplied config.

  - `agent_id` is system-supplied by `Sagents.Session` (derived from
    `conversation_id` via the host's `agent_id_fun`).
  - `config` is a `%FactoryConfig{}` produced by the paired `FactoryRouter`.
  """
  @impl Sagents.Factory
  def create_agent(agent_id, %FactoryConfig{} = c) do
    Agent.new(
      %{
        agent_id: agent_id,
        scope: c.scope,
        model: ChatModels.main(),
        base_system_prompt: base_system_prompt(c),
        middleware: build_middleware(c),
        tools: [],
        tool_context: c.tool_context
      },
      # Since we specify the full middleware stack, don't add defaults
      replace_default_middleware: true
    )
    |> case do
      {:ok, agent} -> {:ok, agent, []}
      {:error, _reason} = err -> err
    end
  end

  # An interim prompt. The full copilot instructions (§8.3) come with the
  # sheet tools in Phase 8.
  defp base_system_prompt(%FactoryConfig{} = _c) do
    """
    You are a spreadsheet copilot. You help a team plan and analyse the data in
    their sheets.

    Several people may be talking to you in the same conversation. Each user
    message begins with the sender's name in square brackets, like
    "[Alice]: ...". Address people by name when it helps.
    """
  end

  # Order matters: early middleware sees messages first (before_model) and
  # processes responses last (after_model).
  defp build_middleware(%FactoryConfig{} = _c) do
    [
      # Titles are generated in a background task, so this goes first.
      {ConversationTitle, [chat_model: ChatModels.title()]},

      # Compress long conversations to fit the context window.
      Sagents.Middleware.Summarization,

      # Fix dangling tool calls from interrupted conversations.
      Sagents.Middleware.PatchToolCalls
    ]
  end
end
