defmodule SpreadSheetAi.Agents.Factory do
  @behaviour Sagents.Factory

  @moduledoc """
  Builds the spreadsheet copilot agent for a conversation.

  Generated by `mix sagents.setup`, then cut down to what the copilot uses
  (docs/backend-plan.md §7.2):

  - models from `SpreadSheetAi.Agents.ChatModels` (OpenRouter by default,
    a scripted model in tests), with no fallback models;
  - middleware: `ConversationTitle`, `Summarization`, `PatchToolCalls` and
    `SpreadSheetAi.Agents.Middleware.SheetTools` (the sheet tools and the
    `<linked_sheets>` context). There is no filesystem, todo list,
    sub-agents, questions or human-in-the-loop;
  - the copilot instructions of backend-plan §8.3 as the system prompt.

  Pairs with `SpreadSheetAi.Agents.FactoryConfig`, which says what a config
  holds and how to build one.
  """

  alias Sagents.Agent
  alias Sagents.Middleware.ConversationTitle
  alias SpreadSheetAi.Agents.ChatModels
  alias SpreadSheetAi.Agents.FactoryConfig
  alias SpreadSheetAi.Agents.Middleware.SheetTools

  @doc """
  Builds a `%Sagents.Agent{}` from the supplied config.

  - `agent_id` is system-supplied by `Sagents.Session` (derived from
    `conversation_id` via the host's `agent_id_fun`).
  - `config` is a `%FactoryConfig{}` produced by the paired `FactoryRouter`.
  """
  @impl Sagents.Factory
  def create_agent(agent_id, %FactoryConfig{} = c) do
    Agent.new(
      %{
        agent_id: agent_id,
        scope: c.scope,
        model: ChatModels.main(),
        base_system_prompt: base_system_prompt(c),
        middleware: build_middleware(c),
        tools: [],
        tool_context: c.tool_context
      },
      # Since we specify the full middleware stack, don't add defaults
      replace_default_middleware: true
    )
    |> case do
      {:ok, agent} -> {:ok, agent, []}
      {:error, _reason} = err -> err
    end
  end

  defp base_system_prompt(%FactoryConfig{} = _c) do
    """
    You are a spreadsheet copilot. You help a team plan and analyse the data in
    their sheets by reading and changing them with your tools.

    Speakers: several people may be talking to you in the same conversation.
    Each user message begins with the sender's name in square brackets, like
    "[Alice]: ...". Address people by name when it helps.

    Sheets: a sheet has one line-item column (text) that labels each row, and
    other columns of type text, number, boolean or date. Tools name rows by
    their label and columns by their name. The sheets this conversation uses
    are listed in the <linked_sheets> block at the start of the latest user
    message, with their ids, columns and row counts. Only work with those
    sheets, or with sheets you find through list_sheets and open with
    open_sheet. Create a new sheet with create_sheet only when asked to.

    Reading: <linked_sheets> holds no values. Read values with read_rows,
    read_cells or find_rows, and never guess them. Keep reads small: read only
    the rows and columns you need.

    Writing: prefer one set_cells or add_rows call with many values over many
    small calls. create_sheet can add columns and rows in the same call.
    Values are literals of the column's type: numbers as numbers, booleans as
    true or false, dates as YYYY-MM-DD, and null to clear a cell. Formulas are
    not supported: compute results yourself and write the values.

    Errors: a tool result that starts with ERROR means nothing was changed. Read
    it, fix the arguments (it often lists the valid names), and call the tool
    again. Don't give up after one error.

    After changing a sheet, say briefly what you changed.
    """
  end

  # Order matters: early middleware sees messages first (before_model) and
  # processes responses last (after_model).
  defp build_middleware(%FactoryConfig{} = _c) do
    [
      # Titles are generated in a background task, so this goes first.
      {ConversationTitle, [chat_model: ChatModels.title()]},

      # Compress long conversations to fit the context window.
      Sagents.Middleware.Summarization,

      # Fix dangling tool calls from interrupted conversations.
      Sagents.Middleware.PatchToolCalls,

      # The sheet tools, and the linked sheets at the start of each run.
      SheetTools
    ]
  end
end
