# This file is responsible for configuring your application
# and its dependencies with the aid of the Config module.
#
# This configuration file is loaded before any dependency and
# is restricted to this project.

# General application configuration
import Config

config :spread_sheet_ai,
  namespace: SpreadSheetAi,
  ecto_repos: [SpreadSheetAi.Repo],
  generators: [timestamp_type: :utc_datetime]

# Configure the endpoint
config :spread_sheet_ai, SpreadSheetAiWeb.Endpoint,
  url: [host: "localhost"],
  adapter: Bandit.PhoenixAdapter,
  render_errors: [
    formats: [html: SpreadSheetAiWeb.ErrorHTML, json: SpreadSheetAiWeb.ErrorJSON],
    layout: false
  ],
  pubsub_server: SpreadSheetAi.PubSub,
  live_view: [signing_salt: "7yLF+0Ai"]

# Configure the mailer
#
# By default it uses the "Local" adapter which stores the emails
# locally. You can see the emails in your browser, at "/dev/mailbox".
#
# For production it's recommended to configure a different adapter
# at the `config/runtime.exs`.
config :spread_sheet_ai, SpreadSheetAi.Mailer, adapter: Swoosh.Adapters.Local

# Configure Elixir's Logger
config :logger, :default_formatter,
  format: "$time $metadata[$level] $message\n",
  metadata: [
    :request_id,
    :user_id,
    :session_id,
    :current_member_id,
    :organization_id,
    :reason,
    :step,
    :code,
    :status,
    :method,
    :path
  ]

# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason

# Auth — generated by `mix phoenix_vue.gen.auth`.
config :spread_sheet_ai, :auth,
  session_cookie_name: "_spread_sheet_ai_auth",
  session_max_age_days: 30,
  password_min_length: 8,
  password_max_length: 128,
  failed_signin_threshold: 5,
  failed_signin_lockout_minutes: 15,
  email_verification_token_ttl_minutes: 60 * 24,
  password_reset_token_ttl_minutes: 60,
  mail_from: {"SpreadSheetAi", "noreply@example.com"}

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{config_env()}.exs"
