import Config

# Configure your database
config :spread_sheet_ai, SpreadSheetAi.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "spread_sheet_ai_dev",
  port: 6432,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :spread_sheet_ai, SpreadSheetAiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "OTB48+H+HJKfX+LC6f0Q+XG5i9VqmKNG2q76zMoWSLgugf0OGp1qMtfL+rFHfbHo",
  watchers: [
    node: ["vite-dev.mjs", cd: Path.expand("../frontend", __DIR__)]
  ]

# Vite dev server config. The root.html.heex reads this to decide whether to
# inject //{request_host}:{port}/@vite/client + /src/main.ts script tags (dev)
# or the digested /assets/main.{js,css} (prod, when this is unset).
#
# `allowed_hosts` is an opt-in list of additional Host: header values that
# AssignRequestHost will accept verbatim. Use it for Tailscale MagicDNS names
# or LAN hostnames you reach the dev server from. Loopback / 0.0.0.0 / ::1 /
# any IP literal are always allowed without listing them here.
config :spread_sheet_ai, :vite_dev_server,
  enabled: true,
  port: 4001,
  allowed_hosts: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :spread_sheet_ai, SpreadSheetAiWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/spread_sheet_ai_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :spread_sheet_ai, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
