defmodule SpreadSheetAiWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :spread_sheet_ai

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_spread_sheet_ai_key",
    signing_salt: "TlIJ5QJS",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # `auth_token` must sit at the TOP level, not inside `websocket:`.
  # Phoenix.Endpoint.socket_paths/4 reads `opts[:auth_token]` from here and
  # then `Keyword.put`s it onto the websocket config, so a nested value is
  # silently overwritten with nil and `connect_info` arrives without the
  # token. ChannelCase injects connect_info directly, so channel tests pass
  # either way — only a real handshake catches it.
  socket "/socket", SpreadSheetAiWeb.UserSocket,
    auth_token: true,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :spread_sheet_ai,
    gzip: not code_reloading?,
    only: SpreadSheetAiWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :spread_sheet_ai
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug SpreadSheetAiWeb.Router
end
