defmodule SpreadSheetAiWeb.Router do
  use SpreadSheetAiWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug SpreadSheetAiWeb.Plugs.AssignRequestHost
    plug :fetch_live_flash
    plug :put_root_layout, html: {SpreadSheetAiWeb.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :protect_from_forgery
    plug SpreadSheetAiWeb.Plugs.FetchUserSession
  end

  # Generated by `mix phoenix_vue.gen.auth`.
  pipeline :require_auth do
    plug SpreadSheetAiWeb.Plugs.RequireAuthentication
  end

  pipeline :require_member do
    plug SpreadSheetAiWeb.Plugs.RequireMember
  end

  # Generated by `mix phoenix_vue.gen.auth`.
  scope "/api", SpreadSheetAiWeb.Api do
    pipe_through :api

    # Public — no session required.
    post "/auth/register", RegistrationController, :create
    post "/sessions", SessionsController, :create
    post "/me/password-reset", PasswordController, :request_reset
    post "/me/password-reset/confirm", PasswordController, :confirm_reset
    post "/me/email-verification/confirm", EmailVerificationController, :confirm
    post "/me/email-verification/resend", EmailVerificationController, :resend
  end

  scope "/api", SpreadSheetAiWeb.Api do
    pipe_through [:api, :require_auth]

    get "/me", MeController, :show
    get "/socket_token", SocketTokenController, :show
    delete "/sessions/current", SessionsController, :delete_current
    post "/sessions/revoke-all", SessionsController, :revoke_all
    post "/me/switch-organization", SessionsController, :switch_organization
    post "/me/change-password", PasswordController, :change
    post "/organizations", OrganizationsController, :create
  end

  # Declare additional /api scopes ABOVE this comment; the SPA catch-all
  # below matches every other path.

  # Enable LiveDashboard and Swoosh mailbox preview in development.
  # Declared BEFORE the SPA catch-all so /dev/* routes match first.
  if Application.compile_env(:spread_sheet_ai, :dev_routes) do
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: SpreadSheetAiWeb.Telemetry
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  # SPA fallback — every browser route renders the same shell so vue-router
  # survives refreshes on deep links. Declared LAST.
  scope "/", SpreadSheetAiWeb do
    pipe_through :browser

    get "/*path", PageController, :home
  end
end
